### ISSUE TITLE
"Humdrum files" directory/folder name

### ISSUE THREAD

**Issue by craigsapp** [jasonleeubc/Cantopop-corpus#1]
Having spaces in directory/file names usually causes problems when processing on the command line.  Can you change this to either `Humdrum` or `Humdrum_files`?

**Comment by jasonleeubc** [comment]
Edited with commit [cd17220](https://github.com/jasonleeubc/Cantopop-corpus/commit/cd17220fbde535250484f6dc71527939b3ac037f)
