### ISSUE TITLE
Filename extensions for Humdrum files

### ISSUE THREAD

**Issue by craigsapp** [jasonleeubc/Cantopop-corpus#3]
Not required, but it would be nice to add a filename extension to the Humdrum files in https://github.com/jasonleeubc/Cantopop-corpus/tree/main/Humdrum%20files

Currently:

```
C0001
C0002
C0003
C0004
C0005
C0101
C0102
C0103
C0104
C0105
C0201
C0202
C0203
C0204
C0205
C0301
C0302
C0303
C0304
C0305
C0401
C0402
C0403
C0404
C0405
C0501
C0502
C0503
C0504
C0505
C0601
C0602
C0603
C0604
C0605
C0701
C0702
C0703
C0704
C0705
C0801
C0802
C0803
C0804
C0805
C0901
C0902
C0903
C0904
C0905
C1001
C1002
C1003
C1004
C1005
C1101
C1102
C1103
C1104
C1105
C1201
C1202
C1203
C1204
C1205
C1301
C1302
C1303
C1304
C1305
C1401
C1402
C1403
C1404
C1405
C1501
C1502
C1503
C1504
C1505
C1601
C1602
C1603
C1604
C1605
C1701
C1702
C1703
C1704
C1705
C1801
C1802
C1803
C1804
C1805
C1901
C1902
C1903
C1904
C1905
C2001
C2002
C2003
C2004
C2005
```

Better would be to add a filename extension, such as `.krn` (to indicate that they have `**kern` contents in them, or `.hmd`. that they are Humdrum files (which contain multiple data types such as `**IPA`), or `.txt` since the are essentially text files.

There is no problem not having filename extensions, but it helps to indicate the basic contents of the files.

To change on the command line, you can do this command in a terminal (if `git` is installed):

```bash
for file in C*
do
     git mv $file $file.krn
done
git commit -am "Add filename extensions to Humdrum data files"
git push
```

**Comment by jasonleeubc** [comment]
Edited with commit [5c160be](https://github.com/jasonleeubc/Cantopop-corpus/commit/5c160be69c1146c608384bcc60523cde8a9fa796)
